# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Afarian Blog
email: jenna@afarian.me
description: A blog website for The Afarian's.
#baseurl: "/phantom-jekyll-theme" # the subpath of your site, e.g. /blog
url: "https://afarianblog.netlify.com" # the base hostname & protocol for your site

# Logo settings
logo-image-url: images/logo.svg
font-awesome-icon-logo:

# Social settings
github_username: j-afarian
twitter_username: jennaafarian
facebook_URL: justbells
instagram_username: bellaruns
dribbble_username: andrewbanchich
500px_username: jennaafarian
phone: 555-5555

# Build settings
markdown: kramdown

# Layout settings
home-link-in-menu: yes
